language: node_js
node_js:
  - '6.1'
addons:
  firefox: "50.0" # fixes https://github.com/mozilla/geckodriver/issues/85
install:
  - npm cache clean
  - npm install
before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # http://www.columbia.edu/~njn2118/journal/2016/10/28.html
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script:
  - npm run jshint
  - npm run build
  - npm run test
  # - npm run codecov # NOTE: commented out because code coverage is so bad that it's not helpful to track how bad it is IMO
deploy:
  provider: npm
  email: mail@theopak.com
  on:
    branch:
      only: master
    tags: true
  api_key:
    secure: VeEgOEeiHBROgfHFmHjK6sJJ0yqydM5EIXNq4gpuhWS6xrPOnR0iD3g4aejNCnlre7F5ld7FetnBAvvPs03lm+oR5Sl2YIRYIGAXPnBEl8zNSWK/uborf/JZ2Vrhn3Er8Evsq6+goZ9U3D8LmrjrjznAS1uY+/KXs9DBL6+064w=
